name: "CI"
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: "Linting"
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/checkout@v5
      - name: Restore Dependency Cache
        id: cache-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            */node_modules
          key: ${{ runner.os }}-dependency-caching-${{ hashFiles('package.json', '*/package.json') }}
      - run: npm ci
      - run: npm run lint

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: "Build Plugin"
    needs:
      - lint
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/checkout@v5
      - name: Restore Dependency Cache
        id: cache-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            */node_modules
          key: ${{ runner.os }}-dependency-caching-${{ hashFiles('package.json', '*/package.json') }}
      - run: npm ci
      - run: npm run build

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    timeout-minutes: 30
    name: "Publish Plugin"
    needs:
      - build
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/checkout@v5
      - name: Restore Dependency Cache
        id: cache-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            */node_modules
          key: ${{ runner.os }}-dependency-caching-${{ hashFiles('package.json', '*/package.json') }}
      - run: npm ci
      - run: npm run prepublishOnly
      - name: 'Semantic Release'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
